WORDS = [
    {"meaning": "安心，放心", "kana": "あんしん", "kanji": "安心", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "安全", "kana": "あんぜん", "kanji": "安全", "pos": "な形容词"},
    {"meaning": "案内，向导", "kana": "あんない", "kanji": "案内", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "意见，想法", "kana": "いけん", "kanji": "意見", "pos": "名词"},
    {"meaning": "医学", "kana": "いがく", "kanji": "医学", "pos": "名词"},
    {"meaning": "以后，将来", "kana": "いご", "kanji": "以後", "pos": "名词"},
    {"meaning": "以前，从前", "kana": "いぜん", "kanji": "以前", "pos": "名词"},
    {"meaning": "以内", "kana": "いない", "kanji": "以内", "pos": "名词"},
    {"meaning": "入口", "kana": "いりぐち", "kanji": "入口", "pos": "名词"},
    {"meaning": "受付，接待处", "kana": "うけつけ", "kanji": "受付", "pos": "名词"},
    {"meaning": "运动", "kana": "うんどう", "kanji": "運動", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "空气，气氛", "kana": "くうき", "kanji": "空気", "pos": "名词"},
    {"meaning": "空港", "kana": "くうこう", "kanji": "空港", "pos": "名词"},
    {"meaning": "经济", "kana": "けいざい", "kanji": "経済", "pos": "名词"},
    {"meaning": "警察", "kana": "けいさつ", "kanji": "警察", "pos": "名词"},
    {"meaning": "经验", "kana": "けいけん", "kanji": "経験", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "计划", "kana": "けいかく", "kanji": "計画", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "研究", "kana": "けんきゅう", "kanji": "研究", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "健康", "kana": "けんこう", "kanji": "健康", "pos": "名词・な形容词"},
    {"meaning": "原因", "kana": "げんいん", "kanji": "原因", "pos": "名词"},
    {"meaning": "玄关", "kana": "げんかん", "kanji": "玄関", "pos": "名词"},
    {"meaning": "公园", "kana": "こうえん", "kanji": "公園", "pos": "名词"},
    {"meaning": "工厂", "kana": "こうじょう", "kanji": "工場", "pos": "名词"},
    {"meaning": "交通", "kana": "こうつう", "kanji": "交通", "pos": "名词"},
    {"meaning": "高校", "kana": "こうこう", "kanji": "高校", "pos": "名词"},
    {"meaning": "国際，国际", "kana": "こくさい", "kanji": "国際", "pos": "名词"},
    {"meaning": "故障", "kana": "こしょう", "kanji": "故障", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "答复，回答", "kana": "こたえ", "kanji": "答え", "pos": "名词"},
    {"meaning": "最近", "kana": "さいきん", "kanji": "最近", "pos": "名词・副词"},
    {"meaning": "最后", "kana": "さいご", "kanji": "最後", "pos": "名词"},
    {"meaning": "最初", "kana": "さいしょ", "kanji": "最初", "pos": "名词"},
    {"meaning": "材料", "kana": "ざいりょう", "kanji": "材料", "pos": "名词"},
    {"meaning": "残念，可惜", "kana": "ざんねん", "kanji": "残念", "pos": "な形容词"},
    {"meaning": "散步", "kana": "さんぽ", "kanji": "散歩", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "时间，时期", "kana": "じき", "kanji": "時期", "pos": "名词"},
    {"meaning": "事故", "kana": "じこ", "kanji": "事故", "pos": "名词"},
    {"meaning": "地震", "kana": "じしん", "kanji": "地震", "pos": "名词"},
    {"meaning": "时代", "kana": "じだい", "kanji": "時代", "pos": "名词"},
    {"meaning": "自动车，汽车", "kana": "じどうしゃ", "kanji": "自動車", "pos": "名词"},
    {"meaning": "准备", "kana": "じゅんび", "kanji": "準備", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "住所", "kana": "じゅうしょ", "kanji": "住所", "pos": "名词"},
    {"meaning": "授业，上课", "kana": "じゅぎょう", "kanji": "授業", "pos": "名词"},
    {"meaning": "招待，邀请", "kana": "しょうたい", "kanji": "招待", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "小说", "kana": "しょうせつ", "kanji": "小説", "pos": "名词"},
    {"meaning": "将来", "kana": "しょうらい", "kanji": "将来", "pos": "名词"},
    {"meaning": "食堂", "kana": "しょくどう", "kanji": "食堂", "pos": "名词"},
    {"meaning": "资料", "kana": "しりょう", "kanji": "資料", "pos": "名词"},
    {"meaning": "新闻", "kana": "しんぶん", "kanji": "新聞", "pos": "名词"},
    {"meaning": "生活", "kana": "せいかつ", "kanji": "生活", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "政治", "kana": "せいじ", "kanji": "政治", "pos": "名词"},
    {"meaning": "世界", "kana": "せかい", "kanji": "世界", "pos": "名词"},
    {"meaning": "说明", "kana": "せつめい", "kanji": "説明", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "战争", "kana": "せんそう", "kanji": "戦争", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "选择", "kana": "せんたく", "kanji": "選択", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "扫除", "kana": "そうじ", "kanji": "掃除", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "咨询，相谈", "kana": "そうだん", "kanji": "相談", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "卒业", "kana": "そつぎょう", "kanji": "卒業", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "大切，重要", "kana": "たいせつ", "kanji": "大切", "pos": "な形容词"},
    {"meaning": "台所，厨房", "kana": "だいどころ", "kanji": "台所", "pos": "名词"},
    {"meaning": "特别", "kana": "とくべつ", "kanji": "特別", "pos": "な形容词・副词"},
    {"meaning": "図書館，图书馆", "kana": "としょかん", "kanji": "図書館", "pos": "名词"},
    {"meaning": "途中，路上", "kana": "とちゅう", "kanji": "途中", "pos": "名词"},
    {"meaning": "必要，必要的", "kana": "ひつよう", "kanji": "必要", "pos": "な形容词"},
    {"meaning": "病院", "kana": "びょういん", "kanji": "病院", "pos": "名词"},
    {"meaning": "普通，一般", "kana": "ふつう", "kanji": "普通", "pos": "名词・な形容词"},
    {"meaning": "文化", "kana": "ぶんか", "kanji": "文化", "pos": "名词"},
    {"meaning": "便利", "kana": "べんり", "kanji": "便利", "pos": "な形容词"},
    {"meaning": "法律", "kana": "ほうりつ", "kanji": "法律", "pos": "名词"},
    {"meaning": "贸易", "kana": "ぼうえき", "kanji": "貿易", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "目的", "kana": "もくてき", "kanji": "目的", "pos": "名词"},
    {"meaning": "理由", "kana": "りゆう", "kanji": "理由", "pos": "名词"},
    {"meaning": "留学", "kana": "りゅうがく", "kanji": "留学", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "料理", "kana": "りょうり", "kanji": "料理", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "旅行", "kana": "りょこう", "kanji": "旅行", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "练习", "kana": "れんしゅう", "kanji": "練習", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "联系，联络", "kana": "れんらく", "kanji": "連絡", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "开始", "kana": "はじめる", "kanji": "始める", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "结束", "kana": "おわる", "kanji": "終わる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "打开，开", "kana": "あける", "kanji": "開ける", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "关上，关闭", "kana": "しめる", "kanji": "閉める", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "进入", "kana": "はいる", "kanji": "入る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "出来，出去", "kana": "でる", "kanji": "出る", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "放入", "kana": "いれる", "kanji": "入れる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "取出，拿出", "kana": "だす", "kanji": "出す", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "换，改变", "kana": "かえる", "kanji": "変える", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "改变，变化", "kana": "かわる", "kanji": "変わる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "记住，记得", "kana": "おぼえる", "kanji": "覚える", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "忘记", "kana": "わすれる", "kanji": "忘れる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "借入，借来", "kana": "かりる", "kanji": "借りる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "借出，贷给", "kana": "かす", "kanji": "貸す", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "帮忙，帮助", "kana": "てつだう", "kanji": "手伝う", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "工作，劳动", "kana": "はたらく", "kanji": "働く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "休息，请假", "kana": "やすむ", "kanji": "休む", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "学习", "kana": "まなぶ", "kanji": "学ぶ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "学习，学会", "kana": "ならう", "kanji": "習う", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "教", "kana": "おしえる", "kanji": "教える", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "调查", "kana": "しらべる", "kanji": "調べる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "考虑", "kana": "かんがえる", "kanji": "考える", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "决定", "kana": "きめる", "kanji": "決める", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "决定，规定", "kana": "きまる", "kanji": "決まる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "发送，送", "kana": "おくる", "kanji": "送る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "收到，接受", "kana": "うける", "kanji": "受ける", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "使用", "kana": "つかう", "kanji": "使う", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "制作，做", "kana": "つくる", "kanji": "作る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "买", "kana": "かう", "kanji": "買う", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "卖", "kana": "うる", "kanji": "売る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "等待", "kana": "まつ", "kanji": "待つ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "拿着，拥有", "kana": "もつ", "kanji": "持つ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "站立", "kana": "たつ", "kanji": "立つ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "坐", "kana": "すわる", "kanji": "座る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "跑", "kana": "はしる", "kanji": "走る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "走路", "kana": "あるく", "kanji": "歩く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "飞", "kana": "とぶ", "kanji": "飛ぶ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "游泳", "kana": "およぐ", "kanji": "泳ぐ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "急忙", "kana": "いそぐ", "kanji": "急ぐ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "死亡", "kana": "しぬ", "kanji": "死ぬ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "玩，游玩", "kana": "あそぶ", "kanji": "遊ぶ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "喝", "kana": "のむ", "kanji": "飲む", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "读", "kana": "よむ", "kanji": "読む", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "说话，讲话", "kana": "はなす", "kanji": "話す", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "写", "kana": "かく", "kanji": "書く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "听，问", "kana": "きく", "kanji": "聞く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "去", "kana": "いく", "kanji": "行く", "pos": "一类动词・特殊", "verb_type": "iku"},
    {"meaning": "来", "kana": "くる", "kanji": "来る", "pos": "三类动词", "verb_type": "kuru"},
    {"meaning": "做", "kana": "する", "kanji": "する", "pos": "三类动词", "verb_type": "suru"},
    {"meaning": "结婚", "kana": "けっこん", "kanji": "結婚", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "出席", "kana": "しゅっせき", "kanji": "出席", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "迟到", "kana": "ちこく", "kanji": "遅刻", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "出发", "kana": "しゅっぱつ", "kanji": "出発", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "到达", "kana": "とうちゃく", "kanji": "到着", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "参观，见学", "kana": "けんがく", "kanji": "見学", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "复习", "kana": "ふくしゅう", "kanji": "復習", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "预习", "kana": "よしゅう", "kanji": "予習", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "检查", "kana": "チェック", "kanji": "チェック", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "复制，复印", "kana": "コピー", "kanji": "コピー", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "预约", "kana": "よやく", "kanji": "予約", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "打电话", "kana": "でんわ", "kanji": "電話", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "说明，解释", "kana": "せつめい", "kanji": "説明", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "介绍", "kana": "しょうかい", "kanji": "紹介", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "翻译", "kana": "ほんやく", "kanji": "翻訳", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "运动", "kana": "うんどう", "kanji": "運動", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "打开，开着", "kana": "あく", "kanji": "開く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "关闭，关着", "kana": "しまる", "kanji": "閉まる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "停，止住", "kana": "とまる", "kanji": "止まる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "停止，停下", "kana": "とめる", "kanji": "止める", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "丢失，失去", "kana": "なくす", "kanji": "無くす", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "消失，不见", "kana": "なくなる", "kanji": "無くなる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "感到疲劳", "kana": "つかれる", "kanji": "疲れる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "担心，困扰", "kana": "こまる", "kanji": "困る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "知道，认识", "kana": "しる", "kanji": "知る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "认为，想", "kana": "おもう", "kanji": "思う", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "寻找", "kana": "さがす", "kanji": "探す", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "选择", "kana": "えらぶ", "kanji": "選ぶ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "搬运，运送", "kana": "はこぶ", "kanji": "運ぶ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "修理", "kana": "なおす", "kanji": "直す", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "治好，改正", "kana": "なおる", "kanji": "直る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "拿走，带走", "kana": "もっていく", "kanji": "持って行く", "pos": "一类动词短语", "verb_type": "phrase"},
    {"meaning": "带来", "kana": "もってくる", "kanji": "持って来る", "pos": "动词短语", "verb_type": "phrase"},
    {"meaning": "穿衣服", "kana": "きる", "kanji": "着る", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "穿鞋/裤子", "kana": "はく", "kanji": "履く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "戴帽子", "kana": "かぶる", "kanji": "被る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "摘下，脱下", "kana": "ぬぐ", "kanji": "脱ぐ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "放，置", "kana": "おく", "kanji": "置く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "排列，并列", "kana": "ならぶ", "kanji": "並ぶ", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "排列，摆放", "kana": "ならべる", "kanji": "並べる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "加上，附加", "kana": "つける", "kanji": "付ける", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "附着，沾上", "kana": "つく", "kanji": "付く", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "够，足够", "kana": "たりる", "kanji": "足りる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "下车", "kana": "おりる", "kanji": "降りる", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "乘坐", "kana": "のる", "kanji": "乗る", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "转乘，换乘", "kana": "のりかえる", "kanji": "乗り換える", "pos": "二类动词", "verb_type": "ichidan"},
    {"meaning": "联系上，接通", "kana": "つながる", "kanji": "繋がる", "pos": "一类动词", "verb_type": "godan"},
    {"meaning": "会议", "kana": "かいぎ", "kanji": "会議", "pos": "名词"},
    {"meaning": "会场", "kana": "かいじょう", "kanji": "会場", "pos": "名词"},
    {"meaning": "会社员", "kana": "かいしゃいん", "kanji": "会社員", "pos": "名词"},
    {"meaning": "课长", "kana": "かちょう", "kanji": "課長", "pos": "名词"},
    {"meaning": "部长", "kana": "ぶちょう", "kanji": "部長", "pos": "名词"},
    {"meaning": "社长", "kana": "しゃちょう", "kanji": "社長", "pos": "名词"},
    {"meaning": "银行员", "kana": "ぎんこういん", "kanji": "銀行員", "pos": "名词"},
    {"meaning": "医生", "kana": "いしゃ", "kanji": "医者", "pos": "名词"},
    {"meaning": "护士", "kana": "かんごし", "kanji": "看護師", "pos": "名词"},
    {"meaning": "教师", "kana": "きょうし", "kanji": "教師", "pos": "名词"},
    {"meaning": "学生", "kana": "がくせい", "kanji": "学生", "pos": "名词"},
    {"meaning": "大学生", "kana": "だいがくせい", "kanji": "大学生", "pos": "名词"},
    {"meaning": "留学生", "kana": "りゅうがくせい", "kanji": "留学生", "pos": "名词"},
    {"meaning": "主妇", "kana": "しゅふ", "kanji": "主婦", "pos": "名词"},
    {"meaning": "独身", "kana": "どくしん", "kanji": "独身", "pos": "名词"},
    {"meaning": "亲戚", "kana": "しんせき", "kanji": "親戚", "pos": "名词"},
    {"meaning": "家族", "kana": "かぞく", "kanji": "家族", "pos": "名词"},
    {"meaning": "兄弟姐妹", "kana": "きょうだい", "kanji": "兄弟", "pos": "名词"},
    {"meaning": "双亲，父母", "kana": "りょうしん", "kanji": "両親", "pos": "名词"},
    {"meaning": "丈夫", "kana": "おっと", "kanji": "夫", "pos": "名词"},
    {"meaning": "妻子", "kana": "つま", "kanji": "妻", "pos": "名词"},
    {"meaning": "女儿", "kana": "むすめ", "kanji": "娘", "pos": "名词"},
    {"meaning": "儿子", "kana": "むすこ", "kanji": "息子", "pos": "名词"},
    {"meaning": "礼物", "kana": "プレゼント", "kanji": "プレゼント", "pos": "名词"},
    {"meaning": "纪念品，土产", "kana": "おみやげ", "kanji": "お土産", "pos": "名词"},
    {"meaning": "纪念", "kana": "きねん", "kanji": "記念", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "照片", "kana": "しゃしん", "kanji": "写真", "pos": "名词"},
    {"meaning": "地图", "kana": "ちず", "kanji": "地図", "pos": "名词"},
    {"meaning": "切符，票", "kana": "きっぷ", "kanji": "切符", "pos": "名词"},
    {"meaning": "车站", "kana": "えき", "kanji": "駅", "pos": "名词"},
    {"meaning": "电车", "kana": "でんしゃ", "kanji": "電車", "pos": "名词"},
    {"meaning": "地下铁", "kana": "ちかてつ", "kanji": "地下鉄", "pos": "名词"},
    {"meaning": "新干线", "kana": "しんかんせん", "kanji": "新幹線", "pos": "名词"},
    {"meaning": "飞机", "kana": "ひこうき", "kanji": "飛行機", "pos": "名词"},
    {"meaning": "船", "kana": "ふね", "kanji": "船", "pos": "名词"},
    {"meaning": "自转车", "kana": "じてんしゃ", "kanji": "自転車", "pos": "名词"},
    {"meaning": "步行", "kana": "とほ", "kanji": "徒歩", "pos": "名词"},
    {"meaning": "邮局", "kana": "ゆうびんきょく", "kanji": "郵便局", "pos": "名词"},
    {"meaning": "银行", "kana": "ぎんこう", "kanji": "銀行", "pos": "名词"},
    {"meaning": "市役所，市政府", "kana": "しやくしょ", "kanji": "市役所", "pos": "名词"},
    {"meaning": "大使馆", "kana": "たいしかん", "kanji": "大使館", "pos": "名词"},
    {"meaning": "美术馆", "kana": "びじゅつかん", "kanji": "美術館", "pos": "名词"},
    {"meaning": "博物馆", "kana": "はくぶつかん", "kanji": "博物館", "pos": "名词"},
    {"meaning": "动物园", "kana": "どうぶつえん", "kanji": "動物園", "pos": "名词"},
    {"meaning": "电影院", "kana": "えいがかん", "kanji": "映画館", "pos": "名词"},
    {"meaning": "旅馆", "kana": "りょかん", "kanji": "旅館", "pos": "名词"},
    {"meaning": "酒店", "kana": "ホテル", "kanji": "ホテル", "pos": "名词"},
    {"meaning": "房间", "kana": "へや", "kanji": "部屋", "pos": "名词"},
    {"meaning": "阳台", "kana": "ベランダ", "kanji": "ベランダ", "pos": "名词"},
    {"meaning": "庭院", "kana": "にわ", "kanji": "庭", "pos": "名词"},
    {"meaning": "钥匙", "kana": "かぎ", "kanji": "鍵", "pos": "名词"},
    {"meaning": "门", "kana": "ドア", "kanji": "ドア", "pos": "名词"},
    {"meaning": "窗户", "kana": "まど", "kanji": "窓", "pos": "名词"},
    {"meaning": "椅子", "kana": "いす", "kanji": "椅子", "pos": "名词"},
    {"meaning": "桌子", "kana": "つくえ", "kanji": "机", "pos": "名词"},
    {"meaning": "书架", "kana": "ほんだな", "kanji": "本棚", "pos": "名词"},
    {"meaning": "信，书信", "kana": "てがみ", "kanji": "手紙", "pos": "名词"},
    {"meaning": "邮票", "kana": "きって", "kanji": "切手", "pos": "名词"},
    {"meaning": "信封", "kana": "ふうとう", "kanji": "封筒", "pos": "名词"},
    {"meaning": "文件", "kana": "しょるい", "kanji": "書類", "pos": "名词"},
    {"meaning": "铅笔", "kana": "えんぴつ", "kanji": "鉛筆", "pos": "名词"},
    {"meaning": "圆珠笔", "kana": "ボールペン", "kanji": "ボールペン", "pos": "名词"},
    {"meaning": "笔记本", "kana": "ノート", "kanji": "ノート", "pos": "名词"},
    {"meaning": "字典", "kana": "じしょ", "kanji": "辞書", "pos": "名词"},
    {"meaning": "电脑", "kana": "パソコン", "kanji": "パソコン", "pos": "名词"},
    {"meaning": "手机", "kana": "けいたい", "kanji": "携帯", "pos": "名词"},
    {"meaning": "资料馆，资料室", "kana": "しりょうしつ", "kanji": "資料室", "pos": "名词"},
    {"meaning": "营业，办公", "kana": "えいぎょう", "kanji": "営業", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "受付员，接待员", "kana": "うけつけがかり", "kanji": "受付係", "pos": "名词"},
    {"meaning": "问题", "kana": "もんだい", "kanji": "問題", "pos": "名词"},
    {"meaning": "回答", "kana": "へんじ", "kanji": "返事", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "问题，提问", "kana": "しつもん", "kanji": "質問", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "考试", "kana": "しけん", "kanji": "試験", "pos": "名词"},
    {"meaning": "合格", "kana": "ごうかく", "kanji": "合格", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "失败，不及格", "kana": "しっぱい", "kanji": "失敗", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "成功", "kana": "せいこう", "kanji": "成功", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "进步", "kana": "しんぽ", "kanji": "進歩", "pos": "名词・する动词", "verb_type": "suru"},
    {"meaning": "退步", "kana": "たいほ", "kanji": "退歩", "pos": "名词・する动词", "verb_type": "suru"},
]
